<?php

namespace Database\Seeders;

use App\Models\Country;
use Illuminate\Database\Seeder;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $usaStates = [
            "01" => "Alabama",
            "02" => "Alaska",
            "03" => "Arizona",
            "04" => "Arkansas",
            "05" => "California",
            "06" => "Colorado",
            "07" => "Connecticut",
            "08" => "Delaware",
            "09" => "Florida",
            "10" => "Georgia",
            "11" => "Hawaii",
            "12" => "Idaho",
            "13" => "Illinois",
            "14" => "Indiana",
            "15" => "Iowa",
            "16" => "Kansas",
            "17" => "Kentucky",
            "18" => "Louisiana",
            "19" => "Maine",
            "20" => "Maryland",
            "21" => "Massachusetts",
            "22" => "Michigan",
            "23" => "Minnesota",
            "24" => "Mississippi",
            "25" => "Missouri",
            "26" => "Montana",
            "27" => "Nebraska",
            "28" => "Nevada",
            "29" => "New Hampshire",
            "30" => "New Jersey",
            "31" => "New Mexico",
            "32" => "New York",
            "33" => "North Carolina",
            "34" => "North Dakota",
            "35" => "Ohio",
            "36" => "Oklahoma",
            "37" => "Oregon",
            "38" => "Pennsylvania",
            "39" => "Rhode Island",
            "40" => "South Carolina",
            "41" => "South Dakota",
            "42" => "Tennessee",
            "43" => "Texas",
            "44" => "Utah",
            "45" => "Vermont",
            "46" => "Virginia",
            "47" => "Washington",
            "48" => "West Virginia",
            "49" => "Wisconsin",
            "50" => "Wyoming",
        ];

        $thailandProvinces = [
            "01" => 'Bangkok',
            "02" => 'Chiang Mai',
            "03" => 'Nakhon Ratchasima',
            "04" => 'Chonburi',
            "05" => 'Phuket',
            "06" => 'Nakhon Si Thammarat',
            "07" => 'Khon Kaen',
            "08" => 'Songkhla',
            "09" => 'Rayong',
            "10" => 'Surat Thani',
            "11" => 'Samut Prakan',
            "12" => 'Samut Sakhon',
            "13" => 'Saraburi',
            "14" => 'Nonthaburi',
            "15" => 'Nakhon Pathom',
            "16" => 'Ayutthaya',
            "17" => 'Lopburi',
            "18" => 'Sukhothai',
            "19" => 'Prachinburi',
            "20" => 'Chachoengsao',
            "21" => 'Nakhon Nayok',
            "22" => 'Singburi',
            "23" => 'Lopburi',
            "24" => 'Phetchaburi',
            "25" => 'Prachuap Khiri Khan',
            "26" => 'Rayong',
            "27" => 'Chumphon',
            "28" => 'Ranong',
            "29" => 'Surat Thani',
            "30" => 'Phang Nga',
            "31" => 'Krabi',
            "32" => 'Phuket',
            "33" => 'Satun',
            "34" => 'Songkhla',
            "35" => 'Yala',
            "36" => 'Pattani',
            "37" => 'Narathiwat',
            "38" => 'Buri Ram',
            "39" => 'Surin',
            "40" => 'Si Sa Ket',
            "41" => 'Ubon Ratchathani',
            "42" => 'Amnat Charoen',
            "43" => 'Yasothon',
            "44" => 'Mukdahan',
            "45" => 'Nakhon Phanom',
            "46" => 'Khon Kaen',
            "47" => 'Loei',
            "48" => 'Nong Bua Lam Phu',
            "49" => 'Udon Thani',
            "50" => 'Sakon Nakhon',
            "51" => 'Nakhon Sawan',
            "52" => 'Phichit',
            "53" => 'Phetchabun',
            "54" => 'Uthai Thani',
            "55" => 'Ratchaburi',
            "56" => 'Kanchanaburi',
            "57" => 'Suphan Buri',
            "58" => 'Nakhon Sawan',
            "59" => 'Sing Buri',
            "60" => 'Ang Thong',
            "61" => 'Lopburi',
            "62" => 'Phra Nakhon Si Ayutthaya',
            "63" => 'Sukhothai',
            "64" => 'Kamphaeng Phet',
            "65" => 'Tak',
            "66" => 'Phang Nga',
            "67" => 'Krabi',
            "68" => 'Surat Thani',
            "69" => 'Chumphon',
            "70" => 'Nakhon Si Thammarat',
            "71" => 'Phatthalung',
            "72" => 'Songkhla',
            "73" => 'Satun',
            "74" => 'Trang',
            "75" => 'Phuket',
            "76" => 'Ranong',
            "77" => 'Chonburi',
        ];

        $germanStates = [
            "01" => "Baden-Württemberg",
            "02" => "Bavaria",
            "03" => "Berlin",
            "04" => "Brandenburg",
            "05" => "Bremen",
            "06" => "Hamburg",
            "07" => "Hesse",
            "08" => "Mecklenburg-Vorpommern",
            "09" => "Lower Saxony",
            "10" => "North Rhine-Westphalia",
            "11" => "Rhineland-Palatinate",
            "12" => "Saarland",
            "13" => "Saxony",
            "14" => "Saxony-Anhalt",
            "15" => "Schleswig-Holstein",
            "16" => "Thuringia",
        ];

        $countries = [
            ['code' => 'geo', 'name' => 'Georgia', 'states' => null],
            ['code' => 'ind', 'name' => 'India', 'states' => null],
            ['code' => 'usa', 'name' => 'United States of America', 'states' => json_encode($usaStates)],
            ['code' => 'ger', 'name' => 'Germany', 'states' => json_encode($germanStates)],
            ['code' => 'tha', 'name' => 'Thailand', 'states' => json_encode($thailandProvinces)],
            ['code' => 'chn', 'name' => 'China', 'states' => null],
            ['code' => 'lao', 'name' => 'Laos', 'states' => null],
            ['code' => 'vnm', 'name' => 'Vietnam', 'states' => null],
            ['code' => 'jpn', 'name' => 'Japan', 'states' => null],
            ['code' => 'kor', 'name' => 'South Korea', 'states' => null],
            ['code' => 'fr', 'name' => 'France', 'states' => null],
            ['code' => 'it', 'name' => 'Italy', 'states' => null],
        ];

        Country::insert($countries);
    }
}
